### ISSUE TITLE
Initialisation des permissions par les extensions

### ISSUE THREAD

**Issue by Xarkam** [SOFTINUX/Base#10]
_From @postb99 on October 16, 2017 6:58_

Les extensions doivent pouvoir insérer des données en complément de DatabaseInitializer dans Security.

Exemple typique : Extension1 va définir une permission extension1_admin et une autre extension1_user, chacune sera utilisée par après, via une policy, pour un élément de menu donné.

On utilise la liste de données "permission" que fournit chaque extension, en ajoutant le fullname de l'assembly de l'extension.  

Prévoir l'insertion avec non duplication, quand l'application démarre (nouvelle interface IDatabaseInitialization avec système de priorités). Modifier l'extension Security pour qu'elle utilise cette interface pour appeler DatabaseInitializer, et le barebone pour qu'il aggrège les initialisations.

_Copied from original issue: OSAMES/Base#7_

**Comment by postb99** [comment]
Fait dans le cadre de la phase 1 de Security : #4

**Comment by postb99** [comment]
Part dans le cadre de #7
