### ISSUE TITLE
Extension d'initialisation

### ISSUE THREAD

**Issue by Xarkam** [SOFTINUX/Base#12]
_From @Xarkam on August 21, 2017 23:5_

Faire une extension qui va initialiser la base applicative et qui peut aussi initialiser un "package".

Un package est la base plus d'autres extensions.

_Copied from original issue: OSAMES/Base#2_

**Comment by Xarkam** [comment]
_From @postb99 on August 22, 2017 11:32_

Pour la base applicative "security" :
- credential types : "login". Prévoir aussi "google_oauth"?

**Comment by Xarkam** [comment]
Pour google auth ou l'OAuth en général, non pas dans l'immédiat. 
On avisera si il y a des demandent pour.

**Comment by postb99** [comment]
Géré dans le cadre de #10, je ferme l'issue.
