### ISSUE TITLE
Menu group section should not display the same as menu item

### ISSUE THREAD

**Issue by Xarkam** [SOFTINUX/Base#16]
Fixer menu generation to highlight sections.

Actual:
![image](https://user-images.githubusercontent.com/331816/33318634-83df5d5a-d43b-11e7-951d-b163beb8aacf.png)
Content and Administration are section.

**Comment by Xarkam** [comment]
Actual state:
![image](https://user-images.githubusercontent.com/331816/33480597-7e0f114c-d691-11e7-9f53-bfa17f3b1a23.png)

**Comment by postb99** [comment]
It looks good
