### ISSUE TITLE
Feature Request: Invoicing

### ISSUE THREAD

**Issue by NicoCG** [SOFTINUX/Base#23]
The ability to generate invoice for user.

**Comment by postb99** [comment]
Hi @NicoCG , please be more explicit about what you have in mind, provide a textual description, a screenshot...
We understand what invoicing means, but what should be invoiced?
Thanks

**Comment by NicoCG** [comment]
I see that one of your entity models are labeled as invoice and I see this is base application for end users I am assuming that invoice model would be used after track is purchased. I am asking if you could provide us an example of invoice generated and sent to customer after track/item has been purchased

**Comment by postb99** [comment]
The entity model with "invoice" has been generated when starting building a sample extension (mini app in the base application) using [Chinook sample database](https://github.com/lerocha/chinook-database).

The "Chinook extension" is unfinished and unfortunately we cannot help you further, invoicing is out of its scope. For your request, didn't you find any interesting existing software? Additionally, your invoice format may vary from a software to another.
