### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [SOFTINUX/Base#25]
Hello! I was just reading through your project and I'd like to contribute to it by designing a logo. If you'd want that too, please let me know if there are any specific things you'd want this logo to represent, and if you don't have any I'll just implement my own ideas. Looking forward to hearing from you :)

**Comment by postb99** [comment]
Hello @newfinal100, thanks for your interest. We need to think about the message the logo has to convey. You did a great job for Valetudo project.

**Comment by newfinal100** [comment]
That's okay, let me know when you decide :)

**Comment by Xarkam** [comment]
Hello @newfinal100 , we will give you our desires within 15 days :)

**Comment by Xarkam** [comment]
Hello @newfinal100 finally we did not have time to work on the logo.

I let you care of making proposals :)
