### ISSUE TITLE
dotnet ef database update build failed

### ISSUE THREAD

**Issue by cedriclange** [SOFTINUX/Base#26]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  1.0.0-preview2-1-003177 [C:\Program Files\dotnet\sdk]
  1.0.0-rc4-004771 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0-preview1-005977 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0-preview1-002111-00 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

## Steps to reproduce
after cloning the project, installing the bundle with npm successfully, the probleme comes when am supposed to create the database in the WebApplication project running the command "dotnet ef database update" the build failed

## Expected  behavior
the migration supposed to work according to the Docs

## Actual behavior
the build fails

**Comment by Xarkam** [comment]
Hello @cedriclange 
I am surprised. I made this manipulation on Saturday on a brand new computer and I did not encounter any problems.

Would it be possible to have the error message provided by the update database?

Thanks.

Note: I bring to your attention that we have a regression on the allocation of permissions. The system does not work anymore.

**Comment by cedriclange** [comment]
Hello @Xarkam , the error message is : build failed when I run this command in the WebApplication project.

When I run it in SoftinuxBase.WebApplication the error is : your startUp project missing a package Microsoft.EntityFrameworkCore.Design, after adding this package nothing works

**Comment by Xarkam** [comment]
I have tested and I not have errors. I would need more information about the errors.
![base](https://user-images.githubusercontent.com/331816/56892540-40fa1480-6a80-11e9-92aa-b762e314918c.gif)

**Comment by cedriclange** [comment]
PS C:\Lemondrop Technology Software\Education-Solution\Base\src\WebApplication> dotnet ef database update
Build failed.
PS C:\Lemondrop Technology Software\Education-Solution\Base\src\WebApplication>
![error](https://user-images.githubusercontent.com/22542802/56897984-40697a00-6a90-11e9-934a-23f1f3e9ad96.gif)
Edit by Xarkam: add gif in post.

**Comment by Xarkam** [comment]
it's not related to creating the database.

Can you simply make `dotnet build -v` in WebApplication folder ?

In my case, the build fails if the npm modules are not present in barebone.
![image](https://user-images.githubusercontent.com/331816/56897861-e23c9700-6a8f-11e9-8077-4e92685396ce.png)

**Comment by cedriclange** [comment]
![error](https://user-images.githubusercontent.com/22542802/56897984-40697a00-6a90-11e9-934a-23f1f3e9ad96.gif)

**Comment by cedriclange** [comment]
![build result](https://user-images.githubusercontent.com/22542802/56898168-a6560180-6a90-11e9-8310-e430cd828223.gif)

**Comment by Xarkam** [comment]
Okay, now in solution folder run `bp.bat bundle`
This command is call before build by the project.

**Comment by cedriclange** [comment]
i will try to change the environement and work in Linux Env and see the outcome, to get more info on where the error coming from.
je te recontacterai demain. A+

**Comment by Xarkam** [comment]
Okay.
I work with windows and linux. I will see if it does not come from the spaces in the path.

Je travaille avec les deux OS. Je regarderai si cela ne vient pas des espaces dans le chemin.

**Comment by Xarkam** [comment]
Spaces in path broke bundle process from batch file.

**Comment by Xarkam** [comment]
Fixed in 8066c1341bad93012b7ae5708b364a99c18a92ec
