### ISSUE TITLE
can Base project work with NetStandard Lib or just .Net Core Class LIb?

### ISSUE THREAD

**Issue by cedriclange** [SOFTINUX/Base#27]
I'm referenceing a NETStandar Lib in NetCore Lib,
am getting a bug like " Can't find the Assembly", so am just wondering if the problem is coming from that?

Edit: merge comment.

**Comment by cedriclange** [comment]
I'm referenceing a NETStandar Lib in NetCore Lib, 
am getting a bug like " Can't find the Assembly", so am just wondering if the problem is coming from that?

**Comment by cedriclange** [comment]
figure out, it can only work with netcoreapp and not netstandard

**Comment by Xarkam** [comment]
Yes, but we still have to check if the change to netstandard does not pose any problems under Linux.

Normally, simply change netcoreapp to netstandard and recompile.
