### ISSUE TITLE
Minified javascript/Release mode: cannot access "n" before initialization

### ISSUE THREAD

**Issue by postb99** [SOFTINUX/Base#39]
**Describe the bug**
As time of writing, the culprit code sits on [NewPermissionsSystem-Admin branch](https://github.com/SOFTINUX/Base/tree/NewPermissionsSystem-Admin). This branch may have been merged to master or deleted at your time of reading.

Minified javascript throws "_cannot access 'n' before initialization_" error when you click in a dropdown list that is enhanced with [Select2](https://select2.org/).

**To Reproduce**
1. Build the application in Release mode. See [our documentation ](https://softinux-base.readthedocs.io/en/latest/installation.html) to seed your local database.
2. Login as johndoe.
2. In main menu, click on 'Main' in section 'Administration'.
3. Click on 'Grant Global Permissions'.
4. Choose a value in the dropdown below "View assigned permissions for:"
5. There is a popup with javascript error.
![image](https://user-images.githubusercontent.com/173565/94734377-712a9e80-0369-11eb-990e-dbd3bb3e6f3f.png)

6. At the right of screen, the assigned permissions look all messy.
![image](https://user-images.githubusercontent.com/173565/94734503-a0411000-0369-11eb-80c6-a1e584572019.png)
They should rather display this way: a list of disabled Select2 dropdowns:
![image](https://user-images.githubusercontent.com/173565/94734708-e72f0580-0369-11eb-9bf6-f98faa573b22.png)

**Expected behavior**
Minified javascript should not throw an error, since non minified javascript works well (build the application in Debug mode).

**Screenshots**
See above

**Environment:**
 - OS: Windows 10
 - Browser: MS Edge, Chrome
 - Version: latest

**Additional context**
Help wished!

**Comment by Xarkam** [comment]
Two minified js files appear to be missing:
![image](https://user-images.githubusercontent.com/331816/94813721-a9c58900-03f8-11eb-8902-541fa744155c.png)
For the admin part, security_user_permissions is necessary because the `viewselectedRole` method called is part of this file:
![image](https://user-images.githubusercontent.com/331816/94813771-b9dd6880-03f8-11eb-9de0-a02bda9ab500.png)

**Comment by Xarkam** [comment]
Error is in
![image](https://user-images.githubusercontent.com/331816/95971006-ea69cd00-0e10-11eb-8da3-d6c2df009e5c.png)
We need to change this for load minified file in release mode.

**Comment by postb99** [comment]
That fixed, a new 404 raised:
![image](https://user-images.githubusercontent.com/173565/96038583-9c33e880-0e67-11eb-8aa4-797c1eba5c42.png)

**Comment by Xarkam** [comment]
Please. Open New issue for this bug :)
