### ISSUE TITLE
Extension Security, phase 1

### ISSUE THREAD

**Issue by Xarkam** [SOFTINUX/Base#4]
_From @Xarkam on August 21, 2017 23:3_

Cette extension gère le login et les droits.
Dans un premier temps :

-  elle possède une partie data layer
-  elle agit en tant que filtre http pour rediriger vers la page de login si on n'est pas authentifié
-  si on est authentifié, alors l'extension fournit un élément de menu "Logout". Relire le tuto sur les claims car on a le thread courant et la session. Etre authentifié = posséder une claim précise.

_Copied from original issue: OSAMES/Base#1_

**Comment by Xarkam** [comment]
L'extension Security n'initialise aucun user.
Elle initialise toutes les tables concernant les "claims", les rôles, les droits, les repository, la base nécessaire dans la table users.

Voir https://github.com/Platformus/Platformus/tree/master/src/Platformus.Security.Data.Entities en exemple.

Penser à créer un extension "d'installation" qui permettra de mettre la base et les extensions fournies.

**Comment by Xarkam** [comment]
_From @postb99 on October 10, 2017 12:39_

#4 features the work around permission manager module and unit testing, it was a lot of work and learning.
Next step is working on integrating http request interception, getting the authenticated state, logging in and off.

**Comment by Xarkam** [comment]
_From @postb99 on October 13, 2017 20:2_

Détails techniques pour l'implémentation :

Réalisation des parties manquantes dans le module Security, et de la partie MVC dans le module Security :
- Scope : page de login, l'authentification, si on est loggué on va sur le dashboard avec un message d'accueil.
- Réaliser notre UserManager (projet Security) + test unitaire
- Réaliser les ViewModel, Controller et vues (projet Security), voir paragraphe "Structuration MVC" de l'analyse détaillée (page Confluence) qui définissent la vue de login et les actions associées.
 - Réaliser les 3 "Actions" dans Security.Actions, (projet Security) qui permettent d'activer l'authentification dans l'application.
    - [ ] Faire fonctionner un attribut "Authorize" dans Extension 1
      - [x] Implémenter Security.Attributes.Authorize qui ne crashe pas si la policy qu'il référence n'existe pas
      - [ ] Paramétrer en DB (par un utilitaire TU) la permission "Admin" de "Extension 1" et l'association au role "Admin". vérifier que l'utilisateur "admin" a accès à la page et "user" a "access denied".

**Comment by postb99** [comment]
Note de dév :
- vérifier et corriger l'insertion effectuée par InitializeDatabase (interversion d'ids ?)
- supprimer les enums faisait référence à des Id d'entitities. Utiliser à la place la recherche

**Comment by postb99** [comment]
Autre note de dev : pour les entités permission, role, entité de lien, etc, ajouter un constructeur avec pour paramètres les informations minimales à fournir pour pouvoir enregistrer un nouvel objet. Cf code des implémentations de IExtensionDatabaseMetadata

**Comment by Xarkam** [comment]
No correspond plus depuis l'utilisation du WIF.
