### ISSUE TITLE
""*Undefined*"bp.bat generateBareboneCss" 

### ISSUE THREAD

**Issue by vhub59** [SOFTINUX/Base#40]
**Describe the bug**
error MSB3073: La commande ""*Undefined*"bp.bat generateBareboneCss" s'est arrêtée avec le code 9009.

**To Reproduce**
1. dotnet build in directory WebApplication

**Screenshots**
![image](https://user-images.githubusercontent.com/36998324/97028222-206b2780-155c-11eb-8720-21b49e3481c5.png)

**Desktop**
 - OS: [Windows NT]

**Comment by Xarkam** [comment]
Fixed in [New permissions system admin](https://github.com/SOFTINUX/Base/pull/49) branch
