### ISSUE TITLE
Add authentication by nickname

### ISSUE THREAD

**Issue by Xarkam** [SOFTINUX/Base#6]
_From @postb99 on October 28, 2017 21:19_

Add a credential type "nickname".

- Fix current value of identifier for "email" credential type, should be "user@softinux.com" rather than "user".
- Update database initialization code (uses same password)
- Handle the new credential type in UserManager's login code
- Adapt the sign in page (label)

_Copied from original issue: OSAMES/Base#12_

**Comment by postb99** [comment]
I close this issue, it's obsolete after we switched to WIF.
